#!/usr/bin/env python

from sys import argv
from sys import exit
from base64 import b64encode
import requests
from json import loads

# https://api.imgur.com/endpoints/image
# https://apidocs.imgur.com/?version=latest

# ./script.py <image.png> ['The title'] ['The description']

#
# ENTER CLIENT ID HERE
#
CLIENT_ID = ''

IMGUR_API_ENDPOINT = 'https://api.imgur.com/3/image'
ARGS_NUM = len(argv)

if ARGS_NUM < 2:
    print("Not enough arguments.")
    exit(1)

with open(argv[1], "rb") as image_file:
    data = image_file.read()

base64_image = b64encode(data)

HEADERS =  {
    'Authorization': 'Client-ID {client_id}'.format(client_id=CLIENT_ID)
}

PAYLOAD = {
    #'':'',
    'image': base64_image,
    'type': 'base64',
    'title': '' if not (ARGS_NUM > 2) else argv[2],
    'description': '' if not (ARGS_NUM > 3) else argv[3],
}

req = requests.post(IMGUR_API_ENDPOINT, data=PAYLOAD, headers=HEADERS)

result = loads(req.text)

for item, value in result['data'].items():
    print("{item:20} {value}".format(item=item, value=value))

#print(result)
